# Change these first
owner: rayandas # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: rayandas.in
    url: https://rayandas.in
  - name: til.rayandas.in
    url: https://til.rayandas.in
  - name: raydeeam.scrollstack.com
    url: https://raydeeam.scrollstack.com
  - name: scrollstack.com
    url: https://scrollstack.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: uptime
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**ScrollStack** Uptime Monitoring."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: ScrollStack
      href: https://scrollstack.com/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
